apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: wordpress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.wordpressDatabase.host }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.wordpressDatabase.name }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.wordpressDatabase.user }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: mariadb-secret
                  key: password
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
